# Generated by Django 5.1.4 on 2025-01-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_part1", models.CharField(max_length=10)),
                ("plate_letter", models.CharField(max_length=2)),
                ("plate_part2", models.CharField(max_length=10)),
                ("plate_code", models.CharField(max_length=10)),
                ("container_part1", models.CharField(max_length=50)),
                ("container_part2", models.CharField(max_length=50)),
                ("container_part3", models.CharField(max_length=50)),
                ("container_part4", models.CharField(max_length=50)),
                ("load_type", models.CharField(max_length=50)),
                ("container_size", models.CharField(max_length=50)),
                ("driver_id", models.CharField(max_length=20)),
                ("driver_confirmed", models.BooleanField(default=False)),
                ("weight", models.CharField(max_length=20)),
                ("seal", models.BooleanField(default=False)),
                ("goods_type", models.CharField(max_length=50)),
                ("route_type", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("invoice_date", models.DateField()),
                ("pass_date", models.DateField()),
            ],
        ),
    ]
