# Generated by Django 5.1.4 on 2025-01-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0002_delete_truck"),
    ]

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_image_front",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vehicle_image_back",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lp_code", models.CharField(blank=True, max_length=50, null=True)),
                ("lp_image", models.CharField(blank=True, max_length=255, null=True)),
                ("plate_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "container_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "container_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("load_type", models.CharField(blank=True, max_length=50, null=True)),
                ("seal", models.BooleanField(default=False)),
                ("imdg", models.BooleanField(default=False)),
                ("driver_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "driver_face",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("entry_direction", models.IntegerField(blank=True, null=True)),
                ("log_time", models.CharField(blank=True, max_length=50, null=True)),
                ("camera_number", models.IntegerField(blank=True, null=True)),
                ("gate_id", models.CharField(blank=True, max_length=50, null=True)),
                ("lp_acc", models.FloatField(blank=True, null=True)),
                ("container_acc", models.FloatField(blank=True, null=True)),
                ("door_direction", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
