# Generated by Django 5.1.4 on 2025-01-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Truck",
        ),
    ]
