# Generated by Django 5.1.4 on 2025-01-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="container_acc",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="truck",
            name="lp_acc",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
